- name: brew install packages
  homebrew: >
    name={{ item.name }}
    state={{ item.state | default('latest') }}
    install_options={{
      item.install_options | default() | join(',')
      if item.install_options is not string
      else item.install_options
    }}
  with_items: "{{ homebrew_packages }}"

- name: symbolic link for java
  file:
    src=/usr/local/opt/openjdk/libexec/openjdk.jdk
    path=/Library/Java/JavaVirtualMachines/openjdk.jdk
    state=link
    force=yes
  become: yes
