- name: brew cask install packages
  homebrew_cask:
    name: "{{ item.name }}"
    state: "{{ item.state|default('installed') }}"
    accept_external_apps: yes
  with_items: "{{ homebrew_cask_packages }}"
