# java environment manager(jdk, gradle,...)
- name: check whether sdkman! installed
  stat: path=~/.sdkman
  register: sdkman_dir
- name: download sdkman! installer
  get_url: url=https://get.sdkman.io dest=/tmp/sdkman-installer.sh
  when: not sdkman_dir.stat.exists
- name: execute the sdkman-installer.sh
  script: /tmp/sdkman-installer.sh
  when: not sdkman_dir.stat.exists
- name: upgrade sdkman!
  shell: source ~/.sdkman/bin/sdkman-init.sh && sdk selfupdate

- name: install gradle
  shell: source ~/.sdkman/bin/sdkman-init.sh && sdk current gradle || sdk install gradle
- name: upgrade gradle
  shell: source ~/.sdkman/bin/sdkman-init.sh && sdk upgrade gradle

# node version manager
- name: download nvm installer
  get_url: url=https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh dest=/tmp/nvm-installer.sh
- name: execute the nvm-installer.sh(install and update)
  script: /tmp/nvm-installer.sh

# python version manager
- name: install and update pyenv
  git:
    repo: https://github.com/yyuu/pyenv.git
    dest: ~/.pyenv

# python virtual environment manager
- name: install and update pyenv-virtualenv
  git:
    repo: https://github.com/yyuu/pyenv-virtualenv.git
    dest: ~/.pyenv/plugins/pyenv-virtualenv

# php version switcher
- name: download php manager
  homebrew: name=brew-php-switcher

# golang version manager
- name: check whether gvm installed
  stat:
    path: ~/.gvm
  register: stat_result
- name: download gvm installer
  get_url: url=https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer dest=/tmp/gvm-installer.sh
- name: execute the gvm-installer.sh(install)
  script: /tmp/gvm-installer.sh
  when: stat_result.stat.exists == False
- name: upgrade gvm
  shell: source "$HOME/.gvm/scripts/gvm" && $HOME/.gvm/bin/gvm get
